README.md, app/src/main/java/com/banuba/example/integrationapp/videoeditor/di/VideoEditorKoinModule.kt, app/src/main/java/com/banuba/example/integrationapp/videoeditor/impl/IntegrationAppRecordingAnimationProvider.kt, app/src/main/java/com/banuba/example/integrationapp/videoeditor/widget/recordbutton/RecordButtonOuterView.kt, app/src/main/java/com/banuba/example/integrationapp/videoeditor/widget/recordbutton/RecordButtonView.kt, app/src/main/java/com/banuba/example/integrationapp/videoeditor/widget/recordbutton/ReverseInterpolator.kt, app/src/main/res/drawable/ic_record_button_inner_oval.xml, app/src/main/res/drawable/ic_record_button_inner_square.xml, mddocs/alert_styles.md, mddocs/audio_content.md, mddocs/camera_styles.md, mddocs/editor_styles.md, mddocs/trimmer_styles.md
Fixed typos, add audio content and stickers content description
=> audio and sticker description

README.md
Описание куда-то пропало. Возвращаю
=> fix export flow description

README.md
Этот ПР нужно будет мержить после обновления до 1.0.14, чтобы можно было предоставить ссылку на реализацию таймера.
=> add timer description

README.md
=> Update README(disable face ar)

app/src/main/res/drawable/ic_volume.xml, app/src/main/res/values/themes.xml
Add adjust audio volume icon for release 1.26.5
=> Add adjust audio volume icon for release 1.26.5

app/build.gradle
=> migrate to 1.26.5.1

mddocs/quickstart.md
remove token storage module from quickstart doc cause its been removed from sdk
=> remove token storage module from quickstart doc

README.md
=> Remove Release section

app/build.gradle, mddocs/quickstart.md
=> Migrate to version 1.37.1

mddocs/quickstart.md
Add packagingOptions settings description
=> Add packagingOptions settings description

app/build.gradle, app/src/main/java/com/banuba/example/integrationapp/MainActivity.kt, mddocs/advanced_integration.md, mddocs/quickstart.md
=> Migrate to 1.40.0

app/build.gradle, mddocs/quickstart.md
=> Migrate to 1.40.2

mddocs/guide_video_editing.md
=> update aspects guide

app/build.gradle, mddocs/quickstart.md
=> Migrate to 1.40.3

app/build.gradle, mddocs/quickstart.md
=> migrate to 1.41.0

app/build.gradle, mddocs/quickstart.md
=> Update ffmpeg version in 1.41. migration

app/build.gradle, mddocs/quickstart.md
=> migrate to 1.41.1

app/build.gradle, mddocs/quickstart.md
=> Migrate to 1.41.2

README.md, app/build.gradle, app/src/main/res/values/themes.xml, build.gradle, mddocs/quickstart.md
update deps, docs and gradle files
=> Migrate to 1.42.0

app/build.gradle, mddocs/quickstart.md
=> migrate to 1.42.0.2

app/build.gradle, mddocs/quickstart.md
=> migrate to 1.42.1

app/build.gradle, mddocs/quickstart.md
=> migrate to version 1.42.2

app/build.gradle, mddocs/quickstart.md
=> migrate to version 1.43.1
